//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aTree.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RegEx_IncludeFilter {
            get {
                return ((string)(this["RegEx_IncludeFilter"]));
            }
            set {
                this["RegEx_IncludeFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RegEx_ExcludeFilter {
            get {
                return ((string)(this["RegEx_ExcludeFilter"]));
            }
            set {
                this["RegEx_ExcludeFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RegEx_IncludeFilterEnabled {
            get {
                return ((bool)(this["RegEx_IncludeFilterEnabled"]));
            }
            set {
                this["RegEx_IncludeFilterEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RegEx_ExcludeFilterEnabled {
            get {
                return ((bool)(this["RegEx_ExcludeFilterEnabled"]));
            }
            set {
                this["RegEx_ExcludeFilterEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Scan_Direction {
            get {
                return ((int)(this["Scan_Direction"]));
            }
            set {
                this["Scan_Direction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string Scan_Levels {
            get {
                return ((string)(this["Scan_Levels"]));
            }
            set {
                this["Scan_Levels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ACL_FolderPath {
            get {
                return ((string)(this["ACL_FolderPath"]));
            }
            set {
                this["ACL_FolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Basic_IncludeFilterEnabled {
            get {
                return ((bool)(this["Basic_IncludeFilterEnabled"]));
            }
            set {
                this["Basic_IncludeFilterEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Basic_ExcludeFilterEnabled {
            get {
                return ((bool)(this["Basic_ExcludeFilterEnabled"]));
            }
            set {
                this["Basic_ExcludeFilterEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Basic_ExcludeFilter {
            get {
                return ((string)(this["Basic_ExcludeFilter"]));
            }
            set {
                this["Basic_ExcludeFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Basic_IncludeFilter {
            get {
                return ((string)(this["Basic_IncludeFilter"]));
            }
            set {
                this["Basic_IncludeFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string Scan_MaxWorkerThreadCount {
            get {
                return ((string)(this["Scan_MaxWorkerThreadCount"]));
            }
            set {
                this["Scan_MaxWorkerThreadCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Scan_EnableCustomThreadParameters {
            get {
                return ((bool)(this["Scan_EnableCustomThreadParameters"]));
            }
            set {
                this["Scan_EnableCustomThreadParameters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string Scan_InterfaceUpdateThrottleMilliseconds {
            get {
                return ((string)(this["Scan_InterfaceUpdateThrottleMilliseconds"]));
            }
            set {
                this["Scan_InterfaceUpdateThrottleMilliseconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Scan_ShowInherited {
            get {
                return ((bool)(this["Scan_ShowInherited"]));
            }
            set {
                this["Scan_ShowInherited"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Scan_ShowFileSize {
            get {
                return ((bool)(this["Scan_ShowFileSize"]));
            }
            set {
                this["Scan_ShowFileSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Scan_ShowFiles {
            get {
                return ((bool)(this["Scan_ShowFiles"]));
            }
            set {
                this["Scan_ShowFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Scan_SimpleNameTranslation {
            get {
                return ((bool)(this["Scan_SimpleNameTranslation"]));
            }
            set {
                this["Scan_SimpleNameTranslation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Scan_TranslationLookupScopes {
            get {
                return ((string)(this["Scan_TranslationLookupScopes"]));
            }
            set {
                this["Scan_TranslationLookupScopes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Filter_IncludeACEs {
            get {
                return ((bool)(this["Filter_IncludeACEs"]));
            }
            set {
                this["Filter_IncludeACEs"] = value;
            }
        }
    }
}
